### PR TITLE
Add cp_load_plugin_descriptor_from_memory()

### PR DESCRIPTION
**Pull request by rbalint**
Kodi/XBMC uses this patch since 2010.

### CODE REVIEW

**Comment by rbalint** [comment]
If you accept the patch please also tag a new release with a minor version bump of the shared library.
That would allow Kodi to start using cpluff without patching it.

**Comment by jlehtine** [comment]
Thank you for the patch. I gladly accept the feature. However, the latest master branch failed to compile with the patch because plug-in descriptor loading has now been moved into pdescriptor.c. I will do some minor refactorization to adjust it for the latest master base and then prepare a new release.

**Comment by jlehtine** [comment]
I have merged both of your pull requests to the master branch. However, the master branch contains a lot of additional new code not included in the 0.1.3 release Kodi has been using so far. Therefore, I have made a separate 0.1.x branch and release 0.1.4 which is pretty much 0.1.3 plus your two pull requests. I am planning to make a 0.2.0 release from the current master branch but before I go ahead with it, it would be great to get some feedback on whether Kodi works with C-Pluff built from the latest master branch.

**Comment by akva2** [comment]
@jlehtine i tried in my fork of kodi, and it seems it's not a drop-in replacement; https://github.com/notspiff/kodi-cmake/commit/483b5beab04ad5b6ea4800e9c035363d764c2741

it is a drop-in replacement as far as compiling is concerned, but no plugins are registered in the cp_scan_plugins() call.

do you see anything in the setup code that has changed? ref https://github.com/notspiff/kodi-cmake/blob/master/xbmc/addons/AddonManager.cpp#L283

which eventually ends up at https://github.com/notspiff/kodi-cmake/blob/master/xbmc/addons/AddonManager.cpp#L613

note that my fork is mostly build system related so the code is the same as mainline kodi.

i'll dig more when i'm not at work but these are my initial findings.

**Comment by rbalint** [comment]
Unfortunately the missing function was not the only divergence in Kodi, there were several internal changes:
https://github.com/xbmc/xbmc/commits/master/lib/cpluff
One is https://github.com/xbmc/xbmc/commit/4e2beb6919e96cbe4a63e8695aa79ec87905c272
which is quite intrusive.
Simply adopting the changes would break C-Pluff's backward compatibility thus I suggest extending the API adding parameters permitting the parsing of Kodi's addon.xml-s.

**Comment by jlehtine** [comment]
I will go through the commits applied to the C-Pluff fork embedded in Kodi and will see how they could be generalized for the standalone C-Pluff without sacrificing backwards compatibility.

**Pull request merged**
